pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = credentials('dockerhub_credentials').username
        DOCKERHUB_PASSWORD = credentials('dockerhub_credentials').password
    }
    stages {
        stage('Docker Login') {
            steps {
                script {
                    // Login to DockerHub
                    sh "echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin"
                }
            }
        }
        stage('Build and Deploy') {
            steps {
                sh '''
                ansible-playbook ansible-playbook.yml
                '''
            }
        }
    }
}
